### ISSUE TITLE
Add orchestration tool for k8

### ISSUE THREAD

**Issue by KaGeN101** [mantl/mantl#1939] opened 2017-04-21 19:29 UTC
Need a way to orchestrate deploys to k8 similar to what Marathon does for Mesos.

We are most definitely going to deploy Spinnaker on the k8 cluster in mantl to achieve this as that is a full blown orchestration pipeline tool. This can then be another tool in the shed.
Spinnaker currently deploys all our infrastructure included our k8 resources

Alternatively Ansible could also be investigated and used.
If you want to orchestrate deploys in sync between mesos and k8 simultaneously you will probably need Ansible or similar in any case to achieve this

**Comment by Cryptophobia** [comment] 2017-04-24 18:46
@KaGeN101 : I am thinking to integrate deis platform (https://github.com/deis/workflow) with an optional ansible playbook as an add-on to put deis workflow on top of k8 and install the deis clients/secrets on the mantl control nodes. 

What does everyone think?

**Comment by KaGeN101** [comment] 2017-04-24 19:02
Deis seem super light weight. Look like they been acquired by Microsoft thou :/

We already got Spinnaker up and running inside the k8 cluster.

We also need something that can deploy resources across both marathon and k8 orchestration

**Comment by kingdonb** [comment] 2017-05-01 01:41
I also vote for Deis.  Workflow doesn't require anything but Helm to get it running.  Users can even delegate platform ingress to Deis as of the latest release.

There is a town-hall meeting every First Thursday of the month and I expect they won't stop just because a silly thing like they got acquired by Microsoft.  You can attend with me on Zoom, I go every month, they're usually 30 minutes or less.

Always comes with a new release.  Stand-up kube experts. :+1: 🌮 🎉  Hope this trend continues.

**Comment by thomasvincent** [comment] 2017-05-01 01:41
Wasn't Deis just bought by MSFT? Not a negative in my opinion. It means the project has strong backing.

**Comment by kingdonb** [comment] 2017-05-01 01:42
It could also mean they will die soon.  I've been following closely though and that's not what I think at all.  Hoping strongly this is the New Microsoft we've all heard about!

**Comment by KaGeN101** [comment] 2017-05-01 09:13
I think they tooling up their OSS shed so should get support, I hope, but you never know with corporates.

Deploying Spinnaker on the k8 is also very simple and then you can pipeline anything onto k8 automatically.

Will should look at deis as well

**Comment by kingdonb** [comment] 2017-05-01 13:42
There is some really good documentation on the Deis blog (deis.com/blog) but most of it is not current.  Tutorials are hard to keep current because the pace of development has been very fast, and Deis devs have never been afraid to quickly and quietly replace parts of the deployment stack when something better comes along.

The latest release had support for replacing Deis' built-in "deis-router" component with a Kubernetes native ingress controller or Traefik.  This was apparently a hotly requested feature.

https://deis.com/blog/2017/april-community-meeting/ - this was the last blog post before the MSFT acquisition was announced.  It says there's a Zoom Town-Hall meeting scheduled for this thursday, May 4, and I assume that's still correct.

The quick-start guide is a good place to start if you've seen Kubernetes but maybe not Helm

https://deis.com/docs/workflow/

There was a great tutorial for GKE that I used that showed how to hook up Compose for database, GCR for Docker Registry, those things are all optional as Deis will arrange for them to be provided in-cluster, but you may save your servers some load by hosting them off-cluster.  These instructions are still based on Helm Classic (helmc); you don't want helmc but they can be trivially adapted to later versions of Workflow and for use with `kubernetes/helm`.

https://deis.com/blog/2016/production-deis-workflow-google-container-engine-pt1/

Next, How to generate self-signed certs for your cluster and hook it up to Cloudflare for free SSL termination...

https://deis.com/blog/2016/production-deis-workflow-google-container-engine-pt2/

Because these docs are blog posts, in many ways they are not as good as the core docs that have a coordinated effort keeping them up-to-date with every new release, but in some ways they go into more depth and show a few ways to use Deis that are not well covered by the core docs.

This was my contribution, almost one year ago, it is now totally obsolete but can still be made to work if you wanted to install a CoreOS with Fleet cluster:

https://deis.com/blog/2016/cheapest-fault-tolerant-cluster-deis/

Because these documents are so quickly obsoleted, most of them don't really tell a full story from end-to-end anymore, that you can reproduce with no prior knowledge by following them exactly.  The fundamentals are easy to get ahold of.

If you didn't want to set up or administer Kubernetes at all, there's also:

https://deis.com/blog/2016/first-kubernetes-cluster-gke/

I would be in favor of contributing a similar "Deis Workflow on Mantl" guide that uses the platform services provided by Mantl instead of hosted cloud services, so far as it is possible, at least!  This definitely seems like an idea that is worth exploring to me.

**Comment by Cryptophobia** [comment] 2017-05-08 13:42
@kingdonb I like your enthusiasm for Dies Workflow.

Deis seems like a great way to go. However, I tried to deploy it on the mantl K8 and was getting various problems with the deis services not being able to come online. However, I was doing this on Vagrant so I assume the latency and booting everything on a single machine with limited resources was not very stable. I removed the Marathon workers completely and got better results after that. (More Deis Workflow services were able to come online)

K8 can use various networking layers on top which makes it very flexible. The following are confirmed to work with Kubernetes:

```
    kopeio-vxlan
    weave
    flannel
    Calico
    Canal (Flannel + Calico)
```

@KaGeN101 : Spinnaker will deploy across both K8 and Marathon, which is very nice but aren't we expanding the scope of this project if we add CI and Deployment tools on top of it. Maybe just providing add-on playbooks with an easy way to run will be good enough in my opinion.

**Comment by kingdonb** [comment] 2017-05-08 13:48
I use the Vagrant too, I will try it out and see if I can replicate your issue.  It is probably a resource reservation / oversubscription issue, if it worked for you as soon as you started closing down Marathon stuff.

**Comment by Cryptophobia** [comment] 2017-05-08 13:51
@kingdonb Yeah, that's what I am thinking. Plus I am using the older helmc with workflow-v2.9.0 so I am not sure if I need to modify the charts and use a different version of workflow.

**Comment by kingdonb** [comment] 2017-05-08 15:09
Definitely.  The older "helmc" predates the adoption of helm as a standard part of Kubernetes core.  All of the new development has moved to using kubernetes/helm, which is tracking newer versions of Kubernetes.

Depending on what version of Kubernetes you have, you may not be ready to switch.  The modern workflow chart is affected by a bug in Kubernetes 1.5.x and 1.6, that wasn't fixed until 1.6.2.

I think you need at least 1.4.x to use the new helm, and I think Mantl 1.3.0 was still using an older version of Kubernetes that didn't have support in the current version of helm, but there was a PR to merge a newer k8s version that can hopefully be included in the next release.

**Comment by Theaxiom** [comment] 2017-09-26 00:14
This will not happen for Mantl 1.x as we are only supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor

**Closed by Theaxiom** 2017-09-26 00:14 UTC
Labels: core/kubernetes, thinking, usability

**Comment by Cryptophobia** [comment] 2017-09-26 12:30
We should make a list for some of these features that users have asked us to support with `Mantl 1.x`, so that we can better cater `endeavor` to the those needs.

**Comment by Theaxiom** [comment] 2017-09-26 16:16
My thoughts exactly @Cryptophobia
