### ISSUE TITLE
504 Gateway timeout for Kubernetes Dashboard UI

### ISSUE THREAD

**Issue by TimWSpence** [mantl/mantl#1799] opened 2016-08-10 12:59 UTC
Hi! We'd love to help you with whatever problem you're having with Mantl. To
help us, please provide the following along with a description of your issue.
You can delete this message once you're done. Thanks!
- Logs from the failing component, if applicable. Might be any of the following:
  - `journalctl --no-pager -l -u <component>`
  - `docker logs <container>`
  - `kubectl logs <pod>`
  - Sandbox logs from the Mesos UI
- Changes made to `sample.yml`, if applicable.
- Ansible version (`ansible --version`):
- Python version (`python --version`):
- Git commit hash or branch:
- Cloud Environment:
- Terraform version (`terraform version`):

**Comment by TimWSpence** [comment] 2016-08-10 13:38
Vagrant version: 1.8.4
Virtualbox version: 5.0.26
OS X version: 10.11.6 (15G31)
[vagrant_up.txt](https://github.com/CiscoCloud/mantl/files/411193/vagrant_up.txt)



Given: clean clone of mantl, master branch
When: I run "vagrant up 2>&1 > ~/vagrant_up.txt"
Then: Mantl ui displays "no services loaded"

vagrant_up.txt attached

**Comment by TimWSpence** [comment] 2016-08-10 13:51
<img width="1436" alt="screen shot 2016-08-10 at 14 50 01" src="https://cloud.githubusercontent.com/assets/3360080/17556056/e370e5d4-5f09-11e6-8784-2c8f2a71a06c.png">

**Comment by ryane** [comment] 2016-08-10 14:08
I cannot repro using vagrant 1.8.4 on osx 10.11.6 (but I am on virtual box 5.0.18). But, I'm curious if you still see that across browser refreshes (try shift+refresh too) and/or a different browser?

If it still occurs, can you check if you are getting any javascript errors in the Chrome developer tools console?

**Comment by ryane** [comment] 2016-08-10 14:12
also, see if you can get to the Consul UI directly (192.168.100.101/consul) to see if your cluster is otherwise healthy.

**Comment by TimWSpence** [comment] 2016-08-10 14:24
Woops that's embarrassing!! Yes, it was a cache issue in Chrome. Thanks!

However, I can't access the kubernetes ui from the mantl ui. Firefox gets a bad gateway?

Consul suggests everything is fine though and I wasn't sure what I needed in ~/.kube/config to try running kubectl against it to test?

**Comment by ryane** [comment] 2016-08-10 14:58
Glad that part is fixed! I am able to reproduce the `504 Gateway Time-out` when trying to load the Kubernetes UI. This does appear to be a bug with our Vagrant setup - We will have to investigate more. In the meantime, you should be able use kubectl to work with kubernetes. Here are the commands I run to set it up:

```
$ kubectl config set-cluster mantl-vagrant --server=https://192.168.100.101/kubeapi --insecure-skip-tls-verify=true
cluster "mantl-vagrant" set.

$ kubectl config set-credentials mantl-vagrant-basic-auth --username=admin --password=yourpw
user "mantl-vagrant-basic-auth" set.

$ kubectl config set-context mantl-vagrant --cluster=mantl-vagrant --user=mantl-vagrant-basic-auth
context "mantl-vagrant" set.

$ kubectl config use-context mantl-vagrant
switched to context "mantl-vagrant".

$ kubectl get nodes
NAME             STATUS                     AGE
control-01       Ready,SchedulingDisabled   1d
kubeworker-001   Ready                      1d
```

(also see https://github.com/CiscoCloud/mantl/tree/master/roles/kubernetes#running-kubectl-remotely)

**Comment by TimWSpence** [comment] 2016-08-10 15:33
Thanks for the help!!

I did get kubectl working locally but it took a fair amount of digging - I didn't set the password so had to find it in /etc/kubernetes/users/known_users.csv.

Also, the above method didn't work for me. I had to point directly to the apiserver listening on 6443, rather than proxying (I'm guessing) through the mantl ui.
After a bit of digging, it seems that the set up is:
- a docker proxy container binds to 0.0.0.0:443 and forwards to the mantl ui container running on 172.17.0.2
- another docker proxy does the same but binding on 0.0.0.0:80
- the mantl ui container listens on ports 80 and 443 and I guess proxies requests to /kubeapi to the kubernetes api server

However, testing this with netcat, I can only connect to 172.17.0.02:80 and not 172.17.0.02:443 (and hence kubectl does not work as the requests don't get proxied)

Do you want any debug output for this?

**Comment by TimWSpence** [comment] 2016-08-10 15:37
Also

16:35 - timspen@TIMSPEN-M-L25T - ~ 
➜  kubectl get po --all-namespaces
NAMESPACE     NAME                                 READY     STATUS             RESTARTS   AGE
kube-system   kube-apiserver-control-01            1/1       Running            0          1h
kube-system   kube-controller-manager-control-01   1/1       Running            0          1h
kube-system   kube-dns-v8-esdmm                    2/2       Running            14         1h
kube-system   kube-podmaster-control-01            2/2       Running            0          1h
kube-system   kube-proxy-control-01                1/1       Running            0          1h
kube-system   kube-proxy-kubeworker-001            1/1       Running            0          1h
kube-system   kube-scheduler-control-01            1/1       Running            0          1h
kube-system   kube2consul-control-01               1/1       Running            0          1h
kube-system   kubernetes-dashboard-2qni7           0/1       CrashLoopBackOff   2          1h

Currently the kubernetes dashboard is in crashloop backoff. Possible reason for the bad gateway?

**Comment by ryane** [comment] 2016-08-10 15:48
What do you get when you run `curl -sku admin:pw https://192.168.100.101/kubeapi/`? Also, what version of Mantl are you on?

> Currently the kubernetes dashboard is in crashloop backoff. Possible reason for the bad gateway?

Definitely. If you run `kubectl --namespace=kube-system logs kubernetes-dashboard-2qni7`, you'll probably see something like 

```
Starting HTTP server on port 9090
Creating API server client for https://kubernetes.service.consul:6443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://kubernetes.service.consul:6443/version: dial tcp: i/o timeout
```

It looks like it is a network/connectivity problem. On Vagrant, kubernetes pods are not able to talk to other cluster services. @Zogg @siddharthist any idea on this?

**Comment by TimWSpence** [comment] 2016-08-10 16:02
I get nothing - as I said, the mantl ui isn't listening on 443:

-bash-4.2# docker ps | grep -i mantlui
6a4e2a06d292        ciscocloud/nginx-mantlui:0.7.1                                    "/scripts/launch.sh"     2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-mantlui
-bash-4.2# docker exec -ti 6a4e2a06d292 bash
bash-4.3# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      35/nginx.conf

I actually don't see any mention of 443 in the nginx config either.

I build this environment from a clean checkout of master.

I do see the dashboard error as you expected.

**Comment by ryane** [comment] 2016-08-10 16:20
Ah, sorry I missed that. Did you disable ssl when you ran `./security-setup`? What do your `*_ssl` settings look like in your security.yml file?

**Comment by TimWSpence** [comment] 2016-08-10 16:39
No worries! The documentation confused me on this as it said all you had to do for vagrant was "vagrant up" so I didn't run security-setup - I just have the defaults (which might explain why I had to find the password for kubernetes in that random csv file...)

Am I supposed to run security-setup for vagrant as well? If so, will running it followed by a "vagrant provision" be enough or do I have to destroy and up again?

**Comment by ChrisAubuchon** [comment] 2016-08-10 16:44
security-setup is run as a part of `vagrant up`. It runs with all security settings disabled.

**Comment by ryane** [comment] 2016-08-10 16:48
yeah, as @ChrisAubuchon said: https://github.com/CiscoCloud/mantl/blob/master/vagrant/provision.sh#L43. so that explains why you didn't have the pw. I don't think this is the cause of the k8s dashboard problem b/c I am seeing the same thing on Vagrant with security enabled. 

It looks like there might be a separate problem with security off and the kubeapi proxy though. I'll try to reproduce that and open another issue for it.

**Comment by TimWSpence** [comment] 2016-08-10 17:00
Thanks, I'll check if running security-setup fixes my kubeapi problem. Can I just run vagrant provision or do I have to vagrant destroy && vagrant up?

**Comment by ryane** [comment] 2016-08-10 17:31
I think you'd be better off destroying and recreating.

**Comment by TimWSpence** [comment] 2016-08-10 20:44
Thanks @ryane. I can confirm that re-building with security-setup fixes the kubectl issue so just the kubernetes dashboard problem left :)

**Comment by TimWSpence** [comment] 2016-08-11 10:54
Also would you mind checking the following on your vagrant cluster:

```
11:29 - timspen@TIMSPEN-M-L25T - ~/dev/bucket/kubernetes/prometheus {master}
➜  kubectl describe svc prometheus-svc
Name:                   prometheus-svc
Namespace:              default
Labels:                 role=service
Selector:               name=prometheus
Type:                   NodePort
IP:                     10.254.87.32
Port:                   <unset> 9090/TCP
NodePort:               <unset> 30752/TCP
Endpoints:              192.168.0.3:9090
Session Affinity:       None
No events.
```

Running 
```
curl $HOSTNAME:30752
```
from the control node gives no response.

I can get it to work through the kube worker node though but my understanding was that both the control and the kube worker node should nat the node port?

**Comment by landgazr** [comment] 2017-03-04 23:31
FWIW - I was always getting the screenshot above after halting and restarting the four nodes. A workaround that seems to work for me so far is to, upon first `vagrant up` from cloning, use [iptables-save](http://askubuntu.com/questions/66890/how-can-i-make-a-specific-set-of-iptables-rules-permanent) on the control node. Then [create a script](http://serverfault.com/questions/200635/linux-iptables-best-way-to-clear-all-rules-leaving-anything-open) to clear iptables. Then, on next bootup, execute the iptables script then [restore iptables](http://askubuntu.com/questions/66890/how-can-i-make-a-specific-set-of-iptables-rules-permanent). I am not sure yet why this works, but it should be a simple matter to automate the task upon `vagrant up`.

**Comment by Theaxiom** [comment] 2017-04-18 23:10
This issue is still occurring.

**Comment by dpavlos** [comment] 2017-04-19 06:57
I am getting the same error on k8s UI as described in https://github.com/mantl/mantl/issues/1799#issuecomment-238906792 and https://github.com/mantl/mantl/issues/1799#issuecomment-238910224 . Investigating a bit further...

**Comment by Cryptophobia** [comment] 2017-04-19 15:18
@Theaxiom @dpavlos I am trying to update the dashboard to a new version but not working and crashing. I think it some kind of service discovery problem with consul...

**Comment by Theaxiom** [comment] 2017-04-19 23:36
Yeah, this is priority number 1 right now. Any updates, please post them here, thanks!

**Comment by Theaxiom** [comment] 2017-04-19 23:57
If anyone requires a local k8 dev environment, minikube is awesome and can run in a single VM on Virtualbox. https://github.com/kubernetes/minikube

If you need help setting it up, let me know.

**Comment by Cryptophobia** [comment] 2017-04-20 13:44
I think there is a credentials issue also, /etc/kubernetes/kubernetes.config is not being set with the right credentials while ~/.kube/config file is being set with the right user and credentials. I will investigate further today...

**Comment by Theaxiom** [comment] 2017-04-20 21:46
I have to build a new hyperkube Docker image: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube -- I am hoping to get that done today.

**Comment by Theaxiom** [comment] 2017-04-24 10:31
I am not going to build a hyperkube image because we can pull those right from Google. Moving forward, we won't need a custom fork of k8.

**Comment by Cryptophobia** [comment] 2017-04-24 17:46
@Theaxiom Okay, sounds good.

**Comment by dpavlos** [comment] 2017-04-25 10:49
This has been fixed in master. Please try the latest mantl release and let us know if the problem still persists.

**Closed by dpavlos** 2017-04-25 10:49 UTC
Labels: bug, core/kubernetes, in progress, provider/gce, provider/vagrant
